# Generated by Django 3.2.8 on 2021-11-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('clientcode', models.IntegerField()),
                ('clientname', models.CharField(max_length=100)),
                ('clienttype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('postalcode', models.IntegerField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('modelnumber', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cell_technology', models.CharField(max_length=30)),
                ('cellmanufacturer', models.CharField(max_length=30)),
                ('numofcell', models.IntegerField()),
                ('numofsellinseriece', models.IntegerField()),
                ('numofseries', models.IntegerField()),
                ('numofdiods', models.IntegerField()),
                ('productlength', models.IntegerField()),
                ('productwidth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('sequenceid', models.AutoField(primary_key=True, serialize=False)),
                ('sequencename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('standardid', models.AutoField(primary_key=True, serialize=False)),
                ('standardname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('publisheddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('officephone', models.IntegerField()),
                ('cellphone', models.IntegerField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('isfirequired', models.CharField(max_length=30)),
                ('fifrequency', models.CharField(max_length=100)),
                ('teststandardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelnum', models.IntegerField()),
                ('maxsysvoltage', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('ics', models.IntegerField()),
                ('vmp', models.IntegerField()),
                ('imp', models.IntegerField()),
                ('pmp', models.IntegerField()),
                ('ff', models.IntegerField()),
                ('testsequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testsequence')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certnumber', models.IntegerField()),
                ('reportnumber', models.IntegerField()),
                ('contactid', models.IntegerField()),
                ('cert_issue_date', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('teststandard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard')),
            ],
        ),
    ]
