# Generated by Django 3.2.8 on 2021-11-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211116_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clientid',
        ),
    ]
