# Generated by Django 3.2.8 on 2021-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='contactid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='reportnumber',
            field=models.CharField(max_length=100),
        ),
    ]
